[package]
name = "halkara"
version = "0.1.1"
edition = "2018"

[dependencies]
clap = "2.33.3"
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
serde = { version = "1.0.127", features = ["derive"] }
cpal = "0.13.3"
crossbeam-channel = "0.5.1"
bytes = "1.0.1"
minimp3 = "0.5.1"
samplerate = "0.2.4"
itertools = "0.10.1"
rand = "0.8.4"

[profile.release]
lto = "fat"
codegen-units = 1
