[package]
name = "halkara"
version = "0.1.5"
edition = "2021"

[dependencies]
clap = "2.34.0"
reqwest = { version = "0.11.8", features = ["blocking", "json"] }
serde = { version = "1.0.132", features = ["derive"] }
bytes = "1.1.0"
rand = "0.8.4"
lazy_static = "1.4.0"
rodio = "0.14.0"

[profile.release]
lto = "fat"
codegen-units = 1
